#Using a python image

FROM python:3.10 

#Declare work directory
WORKDIR /app

#install pandas for the python script
RUN pip install pandas==1.3.5

#Add Python script from our directory
ADD py_script.py .

#Create container volume mounting to host dir so that the python script can read and write data from HOST
VOLUME /app/input
VOLUME /app/output

#create environment variables for python script
ENV INPUT_DIR='/app/input'
ENV OUTPUT_DIR='/app/output'

#To make sure the container keeps on running
CMD tail -f /dev/null